### ISSUE TITLE
Dynamic multiple of height depends on orientation

### ISSUE THREAD

**Issue by tunbeo** [danramteke/DRAutolayout#1]
Hi ! This project is extremely useful. 

I'm trying to create a dynamic view like this :

my question is:
how to set NSLayoutConstraint to make height depends on height of super.view.
For example: 
## | v3 |v4 |v5 |v6 |

landscape orientation

---
## | v5    |  v6  |

portrait orientation

any answer is appreciate me. Thanks

**Comment by danramteke** [comment]
Thank you for the kind words! 

What I have done in the past when I've need to update constraints is this: Remove the view from the super view, and re-add add the view, along with updated constraints. There's probably a better way, but I hope this helps!!

Daniel

**Comment by danramteke** [comment]
In the WWDC '15 Autolayout videos, the presenters suggest adding constraints for all orientations and then using the `activateConstraints` and `deactivateConstraints` API to manage constraints at runtime.
